DROP TABLE IF EXISTS Book;
CREATE TABLE Book (
    isbn INT NOT NULL UNIQUE,
    title VARCHAR(100) NOT NULL UNIQUE,
    subtitle VARCHAR(100),
    author VARCHAR(50),
    PRIMARY KEY(isbn)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;